services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: proyectmathapp-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    restart: unless-stopped
    networks:
      - proyectmathapp-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: proyectmathapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - proyectmathapp-network

networks:
  proyectmathapp-network:
    driver: bridge
